name: Bump Homebrew Cask

on:
  release:
    types: [published]

jobs:
  bump-cask:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release version
        id: release
        run: |
          VERSION=${{ github.event.release.tag_name }}
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Download macOS ARM DMG and calculate SHA256
        id: sha_arm
        run: |
          curl -L -o mirin_arm.dmg https://github.com/ganeshmshetty/mirin/releases/download/${{ github.event.release.tag_name }}/Mirin_${{ steps.release.outputs.VERSION }}_aarch64.dmg
          SHA_ARM=$(sha256sum mirin_arm.dmg | awk '{print $1}')
          echo "SHA_ARM=$SHA_ARM" >> $GITHUB_OUTPUT

      - name: Download macOS x64 DMG and calculate SHA256
        id: sha_x64
        run: |
          curl -L -o mirin_x64.dmg https://github.com/ganeshmshetty/mirin/releases/download/${{ github.event.release.tag_name }}/Mirin_${{ steps.release.outputs.VERSION }}_x64.dmg
          SHA_X64=$(sha256sum mirin_x64.dmg | awk '{print $1}')
          echo "SHA_X64=$SHA_X64" >> $GITHUB_OUTPUT

      - name: Checkout Homebrew Tap Repo
        uses: actions/checkout@v4
        with:
          repository: ganeshmshetty/homebrew-tap
          token: ${{ secrets.TAP_GITHUB_TOKEN }}
          path: tap

      - name: Update Cask File
        run: |
          cat << EOF > tap/Casks/mirin.rb
          cask "mirin" do
            version "${{ steps.release.outputs.VERSION }}"

            if Hardware::CPU.intel?
              sha256 "${{ steps.sha_x64.outputs.SHA_X64 }}"
              url "https://github.com/ganeshmshetty/mirin/releases/download/v#{version}/Mirin_#{version}_x64.dmg"
            else
              sha256 "${{ steps.sha_arm.outputs.SHA_ARM }}"
              url "https://github.com/ganeshmshetty/mirin/releases/download/v#{version}/Mirin_#{version}_aarch64.dmg"
            end

            name "Mirin"
            desc "Modern intuitive screen mirroring interface for Android (scrcpy)"
            homepage "https://github.com/ganeshmshetty/mirin"

            app "Mirin.app"

            zap trash: [
              "~/Library/Application Support/com.mirin.gui",
              "~/Library/Preferences/com.mirin.gui.plist",
              "~/Library/Saved Application State/com.mirin.gui.savedState",
            ]
          end
          EOF

      - name: Commit and Push Cask changes
        run: |
          cd tap
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Casks/mirin.rb
          git commit -m "Update Cask to v${{ steps.release.outputs.VERSION }}"
          git push origin master
